# Generated by Django 4.1.7 on 2023-04-09 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='medical_history',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='clinic_app.medicalhistory'),
        ),
    ]
