# Generated by Django 4.1.7 on 2023-03-26 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0002_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='active',
            new_name='is_active',
        ),
    ]
