# Generated by Django 4.1.7 on 2023-04-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0002_remove_category_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='image',
            field=models.ImageField(null=True, upload_to='static/medicine/'),
        ),
    ]
