# Generated by Django 4.1.7 on 2023-05-03 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0004_clinic_management_db'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='medical_history',
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='shift',
            field=models.CharField(choices=[('Load', 'Đang chờ xác nhận'), ('Confirm', 'Xác nhận'), ('Done', 'Hoàn thành'), ('Cancel', 'Đã hủy')], default='Load', max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='state',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to='static/users/%Y/%m/'),
        ),
    ]
