# Generated by Django 4.1.7 on 2023-05-04 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0005_remove_patient_medical_history_employee_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='position',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
