
# Generated by Django 4.1.7 on 2023-04-22 04:27

from django.db import migrations
from clinic_app.models import (
    Medicine, Category,
)


def add_data(apps, schema_editor):
    categories = ['Tim mạch, tiểu đường, mỡ máu', 'Thuốc bổ và vitamin','Giảm đau, hạ sốt, kháng viêm',
                    'Hô hấp', 'Kháng sinh, kháng nấm', 'Mắt, tai mũi họng','Thần kinh não bộ', 'Tiết niệu sinh dục', 
                    'Tiêu hóa, gan mật', 'Da liễu , dị ứng']
    
    for i in range(10):
        Category.objects.create(category_name= categories[i])
    

    index = 0
    category = Category.objects.get(category_name = categories[index])
    Medicine.objects.create(image = "static/medicine/diamicron.jpg",medicine_name = "Diamicron MR 30mg trị đái tháo đường (2 vỉ x 30 viên)", manufacturer = "Servier", unit_price = "220033" ,description = "Điều trị tiểu đường tuýp II.", category_id = category.id)
    Medicine.objects.create(image = "static/medicine/glucophage.jpg",medicine_name = "Glucophage 850mg trị đái tháo đường (5 vỉ x 20 viên)", manufacturer = "Merck Sante", unit_price = "173005" ,description = "Điều trị tiểu đường tuýp II.", category_id = category.id)
    Medicine.objects.create(image = "static/medicine/concor.jpg",medicine_name = "Concor 2.5mg trị bệnh suy tim mạn tính ổn định (3 vỉ x 10 viên)", manufacturer = "Đức", unit_price = "141115" ,description = "Điều trị bệnh suy tim mạn tính ổn định.", category_id = category.id)
    Medicine.objects.create(image = "static/medicine/vastarel.jpg",medicine_name = "Vastarel MR 35mg trị đau thắt ngực (2 vỉ x 30 viên)", manufacturer = "Les Laboratoiries Servier Industries", unit_price = "292039" ,description = "Điều trị triệu chứng ở bệnh nhân đau thắt ngực ổn định không được kiểm soát đầy đủ.", category_id = category.id)
    Medicine.objects.create(image = "static/medicine/stadovas.jpg",medicine_name = "Stadovas 5 Cap trị tăng huyết áp, đau thắt ngực (3 vỉ x 10 viên)", manufacturer = "Stellapharm", unit_price = "123848" ,description = "Điều trị tăng huyết áp, đau thắt ngực ổn định mạn tính, đau thắt ngực thể co thắt.", category_id = category.id)
    
    category = Category.objects.get(category_name = categories[index+1])
    Medicine.objects.create(image = "static/medicine/enervon.jpg",medicine_name = "Enervon bổ sung vitamin nhóm B và vitamin C hộp 10 vỉ x 10 viên", manufacturer = "United International Pharma", unit_price = "227729" ,description = "Bổ sung vitamin nhóm B và vitamin nhóm C.", category_id = category.id)
    Medicine.objects.create(image = "static/medicine/magne.jpg",medicine_name = "Magne - B6 Corbière trị thiếu magie (5 vỉ x 10 viên)", manufacturer = "Sanofi", unit_price = "212903" ,description = "Điều trị thiếu magnesi riêng biệt hay kết hợp", category_id = category.id)
    Medicine.objects.create(image = "static/medicine/scanneuron.jpg",medicine_name = "Scanneuron - Forte hỗ trợ trị các rối loạn hệ thần kinh (10 vỉ x 10 viên)", manufacturer = "Việt Nam", unit_price = "82990" ,description = "Điều trị hỗ trợ rối loạn về hệ thần kinh như đau dây thần kinh, viêm dây thần kinh mắt,..", category_id = category.id)
    Medicine.objects.create(image = "static/medicine/agi-vita.jpg",medicine_name = "AgiVita- C 500mg phòng và trị bệnh do thiếu vitamin C hộp 10 vỉ x 10 viên", manufacturer = "Agimexpharm", unit_price = "280961" ,description = "Phòng và điều trị thiếu Vitamin C, tăng sức đề kháng, dùng trong thiếu máu do thiếu sắt.", category_id = category.id)
    Medicine.objects.create(image = "static/medicine/vitamin-c.jpg",medicine_name = "Vitamin C Spharm 500mg phòng và trị thiếu vitamin C (10 vỉ x 10 viên)", manufacturer = "Việt Nam", unit_price = "92086" ,description = "Phòng và trị thiếu vitamin C.", category_id = category.id)

    category = Category.objects.get(category_name = categories[index+2])
    Medicine.objects.create(image = "static/medicine/prednisolon.jpg",medicine_name = "Prednisolon Boston 5mg trị các rối loạn viêm và dị ứng lọ 200 viên", manufacturer = "Việt Nam", unit_price = "166901" ,description = "Trị các rối loạn viêm và dị ứng.", category_id = category.id)
    Medicine.objects.create(image = "static/medicine/tana-metrol.jpg",medicine_name = "TanaMetrol 4mg thuốc kháng viêm (3 vỉ x 10 viên)", manufacturer = "Việt Nam", unit_price = "108688" ,description = "Chống viêm, chống dị ứng, trị rối loạn nội tiết.", category_id = category.id)
    Medicine.objects.create(image = "static/medicine/alphachymotrypsine.jpg",medicine_name = "Alpha Chymotrypsine Choay 21µkatals trị phù nề sau chấn thương (2 vỉ x 15 viên)", manufacturer = "Việt Nam", unit_price = "159685" ,description = "Giảm sưng tấy, phù nề.", category_id = category.id)
    Medicine.objects.create(image = "static/medicine/medisolone.jpg",medicine_name = "Medisolone 4mg thuốc kháng viêm (3 vỉ x 10 viên)", manufacturer = "Việt Nam", unit_price = "265695" ,description = "Chống viêm, chống dị ứng, trị rối loạn nội tiết.", category_id = category.id)
    Medicine.objects.create(image = "static/medicine/menison.jpg",medicine_name = "Menison 4mg thuốc kháng viêm (3 vỉ x 10 viên)", manufacturer = "Việt Nam", unit_price = "234010" ,description = "Chống viêm, chống dị ứng, trị rối loạn nội tiết.", category_id = category.id)
    
    category = Category.objects.get(category_name = categories[index+3])
    Medicine.objects.create(image = "static/medicine/eugica-fort.jpg",medicine_name = "Eugica Fort trị ho, đau họng (10 vỉ x 10 viên)", manufacturer = "Dược Hậu Giang", unit_price = "201853" ,description = "Trị ho, đau họng, sổ mũi, sát trùng đường hô hấp, loãng niêm dịch.", category_id = category.id)
    Medicine.objects.create(image = "static/medicine/eugica.jpg",medicine_name = "Eugica trị ho, đau họng (10 vỉ x 10 viên)", manufacturer = "Dược Hậu Giang", unit_price = "214102" ,description = "Dùng điều trị các chứng ho, đau họng, sổ mũi, cảm cúm.", category_id = category.id)
    Medicine.objects.create(image = "static/medicine/philmyrtol.jpg",medicine_name = "Philmyrtol 300 trị viêm phế quản, viêm xoang (6 vỉ x 10 viên)", manufacturer = "Phil Inter Pharma", unit_price = "127629" ,description = "Làm loãng đờm trong viêm phế quản, viêm xoang mũi.", category_id = category.id)
    Medicine.objects.create(image = "static/medicine/acemuc.jpg",medicine_name = "Acemuc 200mg tan đàm trong bệnh lý hô hấp (3 vỉ x 10 viên)", manufacturer = "Sanofi", unit_price = "97256" ,description = "Tiêu chất nhầy phế quản.", category_id = category.id)
    Medicine.objects.create(image = "static/medicine/stacytine.jpg",medicine_name = "Stacytine 200 Cap tan đàm trong bệnh lý hô hấp (10 vỉ x 10 viên)", manufacturer = "Stellapharm", unit_price = "269393" ,description = "Tiêu chất nhầy trong viêm phế quản, giải độc paracetamol.", category_id = category.id)

    category = Category.objects.get(category_name = categories[index+4])
    Medicine.objects.create(image = "static/medicine/klamentin-875-125.jpg",medicine_name = "Klamentin 875/125 trị nhiễm khuẩn (2 vỉ x 7 viên)", manufacturer = "Dược Hậu Giang", unit_price = "132682" ,description = "Điều trị các nhiễm khuẩn do vi khuẩn nhạy cảm.", category_id = category.id)
    Medicine.objects.create(image = "static/medicine/klamentin-500-125.jpg",medicine_name = "Klamentin 500/125 trị nhiễm khuẩn (3 vỉ x 4 viên)", manufacturer = "Dược Hậu Giang", unit_price = "73790" ,description = "Điều trị các nhiễm khuẩn do vi khuẩn nhạy cảm.", category_id = category.id)
    Medicine.objects.create(image = "static/medicine/fonroxil.jpg",medicine_name = "Fonroxil 500mg trị nhiễm khuẩn (3 vỉ x 10 viên)", manufacturer = "Dược Phẩm Hà Tây", unit_price = "248427" ,description = "Trị viêm họng, viêm amidan do liên cầu khuẩn, viêm phế quản phổi, viêm phổi,...", category_id = category.id)
    Medicine.objects.create(image = "static/medicine/tv-cefuroxim.jpg",medicine_name = "TV.Cefuroxime 500mg trị nhiễm khuẩn (3 vỉ x 10 viên)", manufacturer = "Việt Nam", unit_price = "210813" ,description = "Điều trị nhiễm khuẩn thể nhẹ đến vừa.", category_id = category.id)
    Medicine.objects.create(image = "static/medicine/augmentin.jpg",medicine_name = "Augmentin 1g trị nhiễm khuẩn (2 vỉ x 7 viên)", manufacturer = "Glaxo Wellcome Production", unit_price = "94282" ,description = "Diệt vi khuẩn gây bệnh trong cộng đồng và bệnh viện.", category_id = category.id)
   
    category = Category.objects.get(category_name = categories[index+5])
    Medicine.objects.create(image = "static/medicine/sanlein.jpg",medicine_name = "Dung dịch nhỏ mắt Sanlein 0.1 trị rối loạn biểu mô giác mạc lọ 5ml", manufacturer = "Nhật Bản", unit_price = "172041" ,description = "Điều trị bệnh rối loạn biểu mô - giác mạc do khô mắt, đeo kính áp tròng, chấn thương mắt.", category_id = category.id)
    Medicine.objects.create(image = "static/medicine/tobrex.jpg",medicine_name = "Dung dịch nhỏ mắt Tobrex 0.3% trị nhiễm khuẩn mắt chai 5ml", manufacturer = "S.A. Alcon-Couvreur N.V.", unit_price = "80079" ,description = "Điều trị viêm mắt có đáp ứng với steroid, chủng nhạy cảm với tobramycin.", category_id = category.id)
    Medicine.objects.create(image = "static/medicine/tobradex.jpg",medicine_name = "Hỗn dịch nhỏ mắt TobraDex trị nhiễm khuẩn mắt chai 5ml", manufacturer = "S.A. Alcon-Couvreur N.V.", unit_price = "76978" ,description = "Điều trị viêm mắt có đáp ứng với steroid.", category_id = category.id)
    Medicine.objects.create(image = "static/medicine/kary-uni.jpg",medicine_name = "Hỗn dịch nhỏ mắt Kary Uni 0.005% trị đục thủy tinh thể lọ 5ml", manufacturer = "Nhật Bản", unit_price = "226685" ,description = "Điều trị đục thủy tinh thể mới phát ở người lớn tuổi.", category_id = category.id)
    Medicine.objects.create(image = "static/medicine/oflovid.jpg",medicine_name = "Dung dịch nhỏ mắt Oflovid 0.3% trị nhiễm khuẩn mắt chai 5ml", manufacturer = "Nhật Bản", unit_price = "245686" ,description = "Điều trị nhiễm trùng mắt do các chủng nhạy cảm với Ofloxacin.", category_id = category.id)

    category = Category.objects.get(category_name = categories[index+6])
    Medicine.objects.create(image = "static/medicine/gabahasan.jpg",medicine_name = "Gabahasan 300 trị động kinh, đau dây thần kinh (3 vỉ x 10 viên)", manufacturer = "Việt Nam", unit_price = "94449" ,description = "Điều trị hỗ trợ động kinh cục bộ, đau do viêm các dây thần kinh ngoại biên.", category_id = category.id)
    Medicine.objects.create(image = "static/medicine/neustam.jpg",medicine_name = "Neustam 400mg trị chóng mặt, giật rung cơ (10 vỉ x 10 viên)", manufacturer = "Pymepharco", unit_price = "88546" ,description = "Điều trị triệu chứng nhức đầu, rối loạn lo âu, suy giảm trí nhớ, sa sút trí tuệ.", category_id = category.id)
    Medicine.objects.create(image = "static/medicine/premilin.jpg",medicine_name = "Premilin 75mg trị động kinh, đau dây thần kinh (3 vỉ x 10 viên)", manufacturer = "Hasan - Dermapharm", unit_price = "106908" ,description = "Hỗ trợ trong điều trị các cơn động kinh cục bộ, rối loạn lo âu, đau thần kinh.", category_id = category.id)
    Medicine.objects.create(image = "static/medicine/devodil.jpg",medicine_name = "Devodil 50mg trị rối loạn hành vi, triệu chứng lo âu (2 vỉ x 10 viên)", manufacturer = "Cộng hòa Síp", unit_price = "281041" ,description = "Điều trị ngắn hạn triệu chứng lo âu, rối loạn hành vi.", category_id = category.id)
    Medicine.objects.create(image = "static/medicine/nootryl.jpg",medicine_name = "Nootryl 800 trị chóng mặt, giật rung cơ (10 vỉ x 10 viên)", manufacturer = "Việt Nam", unit_price = "160223" ,description = "Hỗ trợ điều trị rung giật, thiếu máu não, chóng mặt, chứng khó đọc ở trẻ.", category_id = category.id)

    category = Category.objects.get(category_name = categories[index+7])
    Medicine.objects.create(image = "static/medicine/domitazol.jpg",medicine_name = "Domitazol trị viêm đường tiết niệu (5 vỉ x 10 viên)", manufacturer = "Việt Nam", unit_price = "273342" ,description = "Hỗ trợ điều trị nhiễm trùng đường tiết niệu dưới không có biến chứng.", category_id = category.id)
    Medicine.objects.create(image = "static/medicine/ketosteril.jpg",medicine_name = "Ketosteril trị rối loạn chuyển hoá protein do suy thận (5 vỉ x 20 viên)", manufacturer = "Labesfal - Laboratórios Almiro, S.A.", unit_price = "267494" ,description = "Phòng và trị rối loạn hoặc suy giảm cơ chế chuyển hoá protein trong bệnh suy thận mạn.", category_id = category.id)
    Medicine.objects.create(image = "static/medicine/no-spa.jpg",medicine_name = "No-Spa 40mg giảm đau do co thắt tiêu hóa (5 vỉ x 10 viên)", manufacturer = "Sanofi", unit_price = "64697" ,description = "Giảm đau do co thắt cơ trơn đường mật, đường tiết niệu, tiêu hóa, đau bụng kinh.", category_id = category.id)
    Medicine.objects.create(image = "static/medicine/expas-forte.jpg",medicine_name = "Expas Forte 80mg giảm đau do co thắt tiêu hóa (3 vỉ x 10 viên)", manufacturer = "Dược Hậu Giang", unit_price = "106091" ,description = "Giảm đau do co thắt cơ trơn đường mật, đường tiết niệu, tiêu hóa, đau bụng kinh.", category_id = category.id)
    Medicine.objects.create(image = "static/medicine/marvelon.jpg",medicine_name = "Marvelon thuốc tránh thai hằng ngày (1 vỉ x 21 viên)", manufacturer = "Hà Lan", unit_price = "148927" ,description = "Tránh thai hằng ngày.", category_id = category.id)

    category = Category.objects.get(category_name = categories[index+8])
    Medicine.objects.create(image = "static/medicine/motilium.jpg",medicine_name = "Motilium-M 10mg trị triệu chứng nôn và buồn nôn (10 vỉ x 10 viên)", manufacturer = "Olic (Thailand) Limited", unit_price = "95590" ,description = "Được chỉ định để điều trị triệu chứng nôn và buồn nôn.", category_id = category.id)
    Medicine.objects.create(image = "static/medicine/omeprazol-20mg-dhg.jpg",medicine_name = "Omeprazol DHG 20mg trị trào ngược dạ dày, thực quản (3 vỉ x 10 viên)", manufacturer = "Việt Nam", unit_price = "291035" ,description = "Trị trào ngược dạ dày-thực quản, loét dạ dày-tá tràng.", category_id = category.id)
    Medicine.objects.create(image = "static/medicine/omeprazole-20mg-stada.jpg",medicine_name = "Omeprazole Stada 20mg trị trào ngược dạ dày, thực quản (3 vỉ x 10 viên)", manufacturer = "Việt Nam", unit_price = "77454" ,description = "Trị viêm loét dạ dày, thực quản, hội chứng Zollinger-Ellison, khó tiêu do tăng tiết acid.", category_id = category.id)
    Medicine.objects.create(image = "static/medicine/omeraz.jpg",medicine_name = "Omeraz 20 trị trào ngược dạ dày, thực quản lọ 28 viên", manufacturer = "Dược phẩm Boston Việt Nam", unit_price = "204393" ,description = "Điều trị hoặc dự phòng tái phát loét dạ dày, tá tràng, viêm thực quản trào ngược.", category_id = category.id)
    Medicine.objects.create(image = "static/medicine/omeprazole.jpg",medicine_name = "Omeprazole Delayed-Release Capsules USP 20mg trị viêm loét dạ dày (10 vỉ x 10 viên)", manufacturer = "Ấn Độ", unit_price = "214099" ,description = "Điều trị loét tá tràng và dạ dày, hội chứng Zollinger Ellison, trào ngược thực quản.", category_id = category.id)

    category = Category.objects.get(category_name = categories[index+9])
    Medicine.objects.create(image = "static/medicine/benoboston.jpg",medicine_name = "BenoBoston trị viêm mũi dị ứng, mày đay lọ 500 viên", manufacturer = "Dược phẩm Boston Việt Nam", unit_price = "258221" ,description = "Trị viêm mũi dị ứng, mày đay.", category_id = category.id)
    Medicine.objects.create(image = "static/medicine/silkron.jpg",medicine_name = "Kem bôi DongkwangSilkron trị nhiễm khuẩn, nhiễm nấm, viêm da tuýp 10g", manufacturer = "Hàn Quốc", unit_price = "182890" ,description = "Trị viêm da, nhiễm nấm, chàm.", category_id = category.id)
    Medicine.objects.create(image = "static/medicine/oracortia.jpg",medicine_name = "Thuốc mỡ Oracortia 0.1% trị viêm nhiễm khoang miệng (50 túi nhôm x 1g)", manufacturer = "Việt Nam", unit_price = "157218" ,description = "Trị viêm loét miệng.", category_id = category.id)
    Medicine.objects.create(image = "static/medicine/bilaxten.jpg",medicine_name = "Bilaxten 20mg trị viêm mũi dị ứng, mày đay (1 vỉ x 10 viên)", manufacturer = "Menarini", unit_price = "67157" ,description = "Trị viêm mũi dị ứng, mày đay.", category_id = category.id)
    Medicine.objects.create(image = "static/medicine/gentrisone.jpg",medicine_name = "Kem bôi Shinpoong Gentri-sone trị viêm da tuýp 20g", manufacturer = "Việt Nam", unit_price = "205769" ,description = "Giảm viêm, ngứa do vi khuẩn nhạy cảm, nấm da.", category_id = category.id)

    
class Migration(migrations.Migration):
    
    dependencies = [
        ('clinic_app', '0006_remove_employee_position_delete_position'),
    ]

    operations = [
        migrations.RunPython(add_data),
    ]