# Generated by Django 4.1.7 on 2023-05-08 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0009_alter_medicine_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='employee',
        ),
    ]
